org: mazenjamshed
app: metahug-node
service: aws-node-express-dynamodb-api-project
frameworkVersion: "3"

custom:
  tableName: "users-table3-${sls:stage}"
  tableNameQuestions: "questions-table4-${sls:stage}"
  tableNameAnything: "anything-table3-${sls:stage}"

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
            - Fn::GetAtt: [QuestionsTable, Arn]
            - Fn::GetAtt: [AnythingTable, Arn]
  environment:
    USERS_TABLE: ${self:custom.tableName}
    QUESTIONS_TABLE: ${self:custom.tableNameQuestions}
    ANYTHING_TABLE: ${self:custom.tableNameAnything}
  httpApi:
    cors: true

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

    QuestionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: questionId
            AttributeType: S # Assuming questions have string IDs
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: questionId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameQuestions}

    AnythingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S # Assuming questions have string IDs
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameAnything}
